#!/usr/bin/env bash

TMPFILE=""

_stop()
{
   if [ -n "${TMPFILE}" ]
   then
      rm "${TMPFILE}"
   fi
   exit 1
}

# Displays help
usage()
{
   echo "Usage : $0 [--version|--description]"
   exit 1;
}
 
if [ $# -gt 1 ]
then
   usage
fi
 
if [ $# -eq 1 ]
then
   OPTION=$1
   
   if [ "--version" = "$OPTION" ]
   then
      echo "tv_grab_iptv version 0.1, 2019/08/08 22:00:00"
      exit
   fi
 
   if [ "--description" = "$OPTION" ]
   then
        echo "Generic XmlTV EPG grabber for IPTV."
        exit
   fi

   if [ "--capabilities" = "$OPTION" ]
   then
        echo "baseline manualconfig"
        exit
   fi
 
   usage
fi

if [ -n "${XMLTV_EPG_URL}" ]
then

    # Zip file name, with current process PID
    TMPFILE="/tmp/$$.xmltv"

    # Nice cleanup in case of interrupt
    trap "_stop" 1 2 3 15

    # Downloading XmlTV data
    wget -q "${XMLTV_EPG_URL}" -O "${TMPFILE}"

    # Send TV guide to standard output
    gunzip -c ${TMPFILE}

    # Cleanup
    rm "${TMPFILE}"
fi

