#!/usr/bin/env sh

TMPFILE=""

_stop()
{
   if [ -n "${TMPFILE}" ]
   then
      rm "${TMPFILE}"
   fi
   exit 1
}

# Displays help
usage()
{
   echo "Usage : $0 [--version|--description]"
   exit 1;
}
 
if [ $# -gt 1 ]
then
   usage
fi
 
if [ $# -eq 1 ]
then
   OPTION=$1
   
   if [ "--version" = "$OPTION" ]
   then
      echo "tv_grab_iptv_sd version 0.1, 2018/11/24 15:30:00"
      exit
   fi
 
   if [ "--description" = "$OPTION" ]
   then
        echo "Generic XmlTV EPG grabber for IPTV using Schedule Direct data."
        exit
   fi

   if [ "--capabilities" = "$OPTION" ]
   then
        echo "baseline manualconfig"
        exit
   fi
 
   usage
fi

# If SD_CONF environment variables point to an existing file
# Then output data from schedules direct grabber
LOCAL_SD_CONF=${SD_CONF:-"/data/conf/sd_grab.conf"}
if [ -f "${LOCAL_SD_CONF}" ]
then
    /usr/bin/tv_grab_zz_sdjson --config-file "${LOCAL_SD_CONF}" --days 15 --output /dev/stdout
fi

