#!/usr/bin/env bash

TMPFILE=""

_stop()
{
   if [ -n "${TMPFILE}" ]
   then
      rm "${TMPFILE}"
   fi
   exit 1
}

# Displays help
usage()
{
   echo "Usage : $0 [--version|--description]"
   exit 1;
}
 
if [ $# -gt 1 ]
then
   usage
fi
 
if [ $# -eq 1 ]
then
   OPTION=$1
   
   if [ "--version" = "$OPTION" ]
   then
      echo "tv_grab_iptv version 0.1, 2018/05/20 21:30:00"
      exit
   fi
 
   if [ "--description" = "$OPTION" ]
   then
        echo "Generic XmlTV EPG grabber for IPTV."
        exit
   fi

   if [ "--capabilities" = "$OPTION" ]
   then
        echo "baseline manualconfig"
        exit
   fi
 
   usage
fi

if [ -n "${XMLTV_EPG_URL}" ]
then

    # Zip file name, with current process PID
    TMPFILE="/tmp/$$.xmltv"

    # Nice cleanup in case of interrupt
    trap "_stop" 1 2 3 15

    # Downloading XmlTV data
    wget -q "${XMLTV_EPG_URL}" -O "${TMPFILE}"

    # Send TV guide to standard output
    cat ${TMPFILE}

    # Cleanup
    rm "${TMPFILE}"
fi

# If SD_CONF environment variables point to an existing file
# Then output data from schedules direct grabber
LOCAL_SD_CONF=${SD_CONF:-"/data/conf/sd_grab.conf"}
if [ -f "${LOCAL_SD_CONF}" ]
then
    /usr/bin/tv_grab_zz_sdjson --config-file "${LOCAL_SD_CONF}" --days 15 --output /dev/stdout 2> /dev/null
fi

